// Generated by swift_ffi. Do not edit.
//
// TypeScript bindings for the `SwiftUI` Swift module compiled to a
// WebAssembly reactor. Load with:
//
//   const bridge = await load(wasmBytesOrModule);
//
// Ownership follows the swift-java model: wrapper objects own a +1 handle
// to the Swift instance. Release deterministically with `close()` (or a
// `using` declaration); a FinalizationRegistry backstop releases leaked
// wrappers after they are garbage collected.
//
// The shared runtime (swift_ffi/runtime/ts) is staged next to this file
// by the wasm library macro; bridges in one directory share the one copy.
import { BlobReader, BlobWriter, Runtime, SwiftError, Tags, Types, decodeWith, decoder, encodeError, encodeErrorBlob, encodeWith, errorMessageOf, foreignObjects, nextCallId, pendingCalls, registerForeign, registry, resumeAsync, stageBytes, stageString, takeBytes, wasiShim, } from "./swift_ffi_runtime.js?v=2882800062";
// Re-exported so consumers keep importing them from this module.
export { Types } from "./swift_ffi_runtime.js?v=2882800062";
/** The runtime type token for `TextMetrics` (generic calls). */
export const TextMetricsType = {
    encode(w, v) {
        w.typeHeader(Tags.struct, "TextMetrics");
        w.i64(2n);
        Types.double.encode(w, v.width);
        Types.double.encode(w, v.height);
    },
    decode(r) {
        const tag = r.i32();
        const aux = r.i32();
        if (tag !== Tags.struct)
            throw new SwiftError("expected TextMetrics");
        if (aux > 0)
            r.bytes(aux);
        r.i64();
        const width = Types.double.decode(r);
        const height = Types.double.decode(r);
        return { width, height };
    },
};
/** The runtime type token for `ImageInfoValue` (generic calls). */
export const ImageInfoValueType = {
    encode(w, v) {
        w.typeHeader(Tags.struct, "ImageInfoValue");
        w.i64(3n);
        Types.int32.encode(w, v.state);
        Types.double.encode(w, v.width);
        Types.double.encode(w, v.height);
    },
    decode(r) {
        const tag = r.i32();
        const aux = r.i32();
        if (tag !== Tags.struct)
            throw new SwiftError("expected ImageInfoValue");
        if (aux > 0)
            r.bytes(aux);
        r.i64();
        const state = Types.int32.decode(r);
        const width = Types.double.decode(r);
        const height = Types.double.decode(r);
        return { state, width, height };
    },
};
/** The runtime type token for `StoredValue` (generic calls). */
export const StoredValueType = {
    encode(w, v) {
        w.typeHeader(Tags.struct, "StoredValue");
        w.i64(2n);
        Types.bool.encode(w, v.exists);
        Types.string.encode(w, v.contents);
    },
    decode(r) {
        const tag = r.i32();
        const aux = r.i32();
        if (tag !== Tags.struct)
            throw new SwiftError("expected StoredValue");
        if (aux > 0)
            r.bytes(aux);
        r.i64();
        const exists = Types.bool.decode(r);
        const contents = Types.string.decode(r);
        return { exists, contents };
    },
};
export const PlatformDependencyKeyType = {
    encode(w, v) {
        Types.string.encode(w, v);
    },
    decode(r) {
        return Types.string.decode(r);
    },
};
export class SwiftNetworkService {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_platform_services_NetworkService_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("NetworkService used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_platform_services_NetworkService_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    request(url, method) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.string.encode(w, url);
        Types.string.encode(w, method);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return decodeWith(Types.bytes, blob);
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_NetworkService_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
    send(url, method, headers, body) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.string.encode(w, url);
        Types.string.encode(w, method);
        Types.string.encode(w, headers);
        Types.bytes.encode(w, body);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return decodeWith(Types.bytes, blob);
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_NetworkService_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
    perform(url, method, headers, body) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.string.encode(w, url);
        Types.string.encode(w, method);
        Types.string.encode(w, headers);
        Types.bytes.encode(w, body);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return decodeWith(Types.bytes, blob);
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_NetworkService_invoke", handle, 2, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
}
/** Wraps a consumer-implemented `NetworkService` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_NetworkService(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const callId = Types.int32.decode(r);
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                if (!runtime)
                    throw new SwiftError("NetworkService.request is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.request(a0, a1)).then((value) => resumeAsync(rt(), callId, encodeWith(Types.bytes, value)), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
            case 1: {
                const callId = Types.int32.decode(r);
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                const a2 = Types.string.decode(r);
                const a3 = Types.bytes.decode(r);
                if (!runtime)
                    throw new SwiftError("NetworkService.send is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.send(a0, a1, a2, a3)).then((value) => resumeAsync(rt(), callId, encodeWith(Types.bytes, value)), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
            case 2: {
                const callId = Types.int32.decode(r);
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                const a2 = Types.string.decode(r);
                const a3 = Types.bytes.decode(r);
                if (!runtime)
                    throw new SwiftError("NetworkService.perform is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.perform(a0, a1, a2, a3)).then((value) => resumeAsync(rt(), callId, encodeWith(Types.bytes, value)), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown NetworkService method ordinal");
    };
}
export class SwiftFileService {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_platform_services_FileService_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("FileService used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_platform_services_FileService_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    list(path) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, path);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_FileService_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.array(Types.string), result);
    }
    exists(path) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, path);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_FileService_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.bool, result);
    }
    read(path) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, path);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_FileService_invoke", handle, 2, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.bytes, result);
    }
    write(path, contents) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, path);
        Types.bytes.encode(w, contents);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_FileService_invoke", handle, 3, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.bool, result);
    }
    delete(path) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, path);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_FileService_invoke", handle, 4, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.bool, result);
    }
    url(path) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, path);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_FileService_invoke", handle, 5, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.string, result);
    }
}
/** Wraps a consumer-implemented `FileService` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_FileService(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.string.decode(r);
                return encodeWith(Types.array(Types.string), impl.list(a0));
            }
            case 1: {
                const a0 = Types.string.decode(r);
                return encodeWith(Types.bool, impl.exists(a0));
            }
            case 2: {
                const a0 = Types.string.decode(r);
                try {
                    return encodeWith(Types.bytes, impl.read(a0));
                }
                catch (error) {
                    return encodeError(error instanceof Error ? error.message : String(error));
                }
            }
            case 3: {
                const a0 = Types.string.decode(r);
                const a1 = Types.bytes.decode(r);
                return encodeWith(Types.bool, impl.write(a0, a1));
            }
            case 4: {
                const a0 = Types.string.decode(r);
                return encodeWith(Types.bool, impl.delete(a0));
            }
            case 5: {
                const a0 = Types.string.decode(r);
                return encodeWith(Types.string, impl.url(a0));
            }
        }
        throw new SwiftError("unknown FileService method ordinal");
    };
}
export class SwiftKeychainService {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_platform_services_KeychainService_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("KeychainService used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_platform_services_KeychainService_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    get(key) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.string.encode(w, key);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return decodeWith(Types.bytes, blob);
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_KeychainService_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
    set(value, for_) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.bytes.encode(w, value);
        Types.string.encode(w, for_);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return undefined;
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_KeychainService_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
    delete(key) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.string.encode(w, key);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return undefined;
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_KeychainService_invoke", handle, 2, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
}
/** Wraps a consumer-implemented `KeychainService` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_KeychainService(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const callId = Types.int32.decode(r);
                const a0 = Types.string.decode(r);
                if (!runtime)
                    throw new SwiftError("KeychainService.get is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.get(a0)).then((value) => resumeAsync(rt(), callId, encodeWith(Types.bytes, value)), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
            case 1: {
                const callId = Types.int32.decode(r);
                const a0 = Types.bytes.decode(r);
                const a1 = Types.string.decode(r);
                if (!runtime)
                    throw new SwiftError("KeychainService.set is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.set(a0, a1)).then((value) => resumeAsync(rt(), callId, new Uint8Array([0, 0, 0, 0, 0, 0, 0, 0])), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
            case 2: {
                const callId = Types.int32.decode(r);
                const a0 = Types.string.decode(r);
                if (!runtime)
                    throw new SwiftError("KeychainService.delete is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.delete(a0)).then((value) => resumeAsync(rt(), callId, new Uint8Array([0, 0, 0, 0, 0, 0, 0, 0])), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown KeychainService method ordinal");
    };
}
export class SwiftAnalyticsService {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_platform_services_AnalyticsService_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("AnalyticsService used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_platform_services_AnalyticsService_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    track(event) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, event);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_AnalyticsService_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
}
/** Wraps a consumer-implemented `AnalyticsService` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_AnalyticsService(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.string.decode(r);
                impl.track(a0);
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown AnalyticsService method ordinal");
    };
}
export class SwiftConfigurationService {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_platform_services_ConfigurationService_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("ConfigurationService used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_platform_services_ConfigurationService_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    flag(key) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, key);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_ConfigurationService_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.bool, result);
    }
}
/** Wraps a consumer-implemented `ConfigurationService` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_ConfigurationService(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.string.decode(r);
                return encodeWith(Types.bool, impl.flag(a0));
            }
        }
        throw new SwiftError("unknown ConfigurationService method ordinal");
    };
}
export class SwiftImagePickerService {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_platform_services_ImagePickerService_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("ImagePickerService used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_platform_services_ImagePickerService_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    pickImage(maxDimension) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.int.encode(w, maxDimension);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return decodeWith(Types.string, blob);
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_ImagePickerService_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
}
/** Wraps a consumer-implemented `ImagePickerService` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_ImagePickerService(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const callId = Types.int32.decode(r);
                const a0 = Types.int.decode(r);
                if (!runtime)
                    throw new SwiftError("ImagePickerService.pickImage is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.pickImage(a0)).then((value) => resumeAsync(rt(), callId, encodeWith(Types.string, value)), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown ImagePickerService method ordinal");
    };
}
export class SwiftDeviceMotionService {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_platform_services_DeviceMotionService_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("DeviceMotionService used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_platform_services_DeviceMotionService_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    nextShake() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return undefined;
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_DeviceMotionService_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
}
/** Wraps a consumer-implemented `DeviceMotionService` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_DeviceMotionService(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const callId = Types.int32.decode(r);
                if (!runtime)
                    throw new SwiftError("DeviceMotionService.nextShake is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.nextShake()).then((value) => resumeAsync(rt(), callId, new Uint8Array([0, 0, 0, 0, 0, 0, 0, 0])), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown DeviceMotionService method ordinal");
    };
}
export class SwiftPreferencesService {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_platform_services_PreferencesService_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("PreferencesService used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_platform_services_PreferencesService_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    get(key) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, key);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_PreferencesService_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.string, result);
    }
    set(key, value) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, key);
        Types.string.encode(w, value);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_PreferencesService_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
}
/** Wraps a consumer-implemented `PreferencesService` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_PreferencesService(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.string.decode(r);
                return encodeWith(Types.string, impl.get(a0));
            }
            case 1: {
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                impl.set(a0, a1);
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown PreferencesService method ordinal");
    };
}
export class SwiftTimerService {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_platform_services_TimerService_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("TimerService used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_platform_services_TimerService_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    delay(milliseconds) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.int32.encode(w, milliseconds);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return undefined;
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_TimerService_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
}
/** Wraps a consumer-implemented `TimerService` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_TimerService(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const callId = Types.int32.decode(r);
                const a0 = Types.int32.decode(r);
                if (!runtime)
                    throw new SwiftError("TimerService.delay is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.delay(a0)).then((value) => resumeAsync(rt(), callId, new Uint8Array([0, 0, 0, 0, 0, 0, 0, 0])), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown TimerService method ordinal");
    };
}
export class SwiftOAuthService {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_platform_services_OAuthService_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("OAuthService used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_platform_services_OAuthService_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    redirectURI() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return decodeWith(Types.string, blob);
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_OAuthService_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
    authorize(url) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const callId = nextCallId();
        Types.int32.encode(w, callId);
        Types.string.encode(w, url);
        const promise = new Promise((resolve, reject) => {
            pendingCalls.set(callId, {
                resolve: resolve,
                decode: (blob) => {
                    const failure = errorMessageOf(blob);
                    if (failure !== null) {
                        reject(new SwiftError(failure));
                        return undefined;
                    }
                    return decodeWith(Types.string, blob);
                },
            });
        });
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_platform_services_OAuthService_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return promise;
    }
}
/** Wraps a consumer-implemented `OAuthService` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_OAuthService(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const callId = Types.int32.decode(r);
                if (!runtime)
                    throw new SwiftError("OAuthService.redirectURI is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.redirectURI()).then((value) => resumeAsync(rt(), callId, encodeWith(Types.string, value)), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
            case 1: {
                const callId = Types.int32.decode(r);
                const a0 = Types.string.decode(r);
                if (!runtime)
                    throw new SwiftError("OAuthService.authorize is async and needs a runtime-bound dispatcher");
                const rt = runtime;
                Promise.resolve().then(() => impl.authorize(a0)).then((value) => resumeAsync(rt(), callId, encodeWith(Types.string, value)), (error) => resumeAsync(rt(), callId, encodeError(error instanceof Error ? error.message : String(error))));
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown OAuthService method ordinal");
    };
}
export class SwiftGPUWebHost {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_GPUWebHost_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("GPUWebHost used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_GPUWebHost_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    gpuCreateTexture(id, width, height, rgba) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.int32.encode(w, id);
        Types.int32.encode(w, width);
        Types.int32.encode(w, height);
        Types.bytes.encode(w, rgba);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuDestroyTexture(id) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.int32.encode(w, id);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuBeginFrame(red, green, blue, alpha) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.double.encode(w, red);
        Types.double.encode(w, green);
        Types.double.encode(w, blue);
        Types.double.encode(w, alpha);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 2, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuSetTransform(matrix) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.bytes.encode(w, matrix);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 3, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuDrawTextured(id, vertices) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.int32.encode(w, id);
        Types.bytes.encode(w, vertices);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 4, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuDrawColor(vertices) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.bytes.encode(w, vertices);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 5, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuDrawRects(vertices) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.bytes.encode(w, vertices);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 6, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuSetScissor(x, y, width, height) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.int32.encode(w, x);
        Types.int32.encode(w, y);
        Types.int32.encode(w, width);
        Types.int32.encode(w, height);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 7, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuClearScissor() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 8, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    gpuEndFrame() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_GPUWebHost_invoke", handle, 9, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
}
/** Wraps a consumer-implemented `GPUWebHost` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_GPUWebHost(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.int32.decode(r);
                const a2 = Types.int32.decode(r);
                const a3 = Types.bytes.decode(r);
                impl.gpuCreateTexture(a0, a1, a2, a3);
                return new Uint8Array(0);
            }
            case 1: {
                const a0 = Types.int32.decode(r);
                impl.gpuDestroyTexture(a0);
                return new Uint8Array(0);
            }
            case 2: {
                const a0 = Types.double.decode(r);
                const a1 = Types.double.decode(r);
                const a2 = Types.double.decode(r);
                const a3 = Types.double.decode(r);
                impl.gpuBeginFrame(a0, a1, a2, a3);
                return new Uint8Array(0);
            }
            case 3: {
                const a0 = Types.bytes.decode(r);
                impl.gpuSetTransform(a0);
                return new Uint8Array(0);
            }
            case 4: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.bytes.decode(r);
                impl.gpuDrawTextured(a0, a1);
                return new Uint8Array(0);
            }
            case 5: {
                const a0 = Types.bytes.decode(r);
                impl.gpuDrawColor(a0);
                return new Uint8Array(0);
            }
            case 6: {
                const a0 = Types.bytes.decode(r);
                impl.gpuDrawRects(a0);
                return new Uint8Array(0);
            }
            case 7: {
                const a0 = Types.int32.decode(r);
                const a1 = Types.int32.decode(r);
                const a2 = Types.int32.decode(r);
                const a3 = Types.int32.decode(r);
                impl.gpuSetScissor(a0, a1, a2, a3);
                return new Uint8Array(0);
            }
            case 8: {
                impl.gpuClearScissor();
                return new Uint8Array(0);
            }
            case 9: {
                impl.gpuEndFrame();
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown GPUWebHost method ordinal");
    };
}
export class SwiftWebHost {
    handle;
    runtime;
    /** @internal Takes ownership of a +1 handle. */
    constructor(runtime, handle) {
        this.runtime = runtime;
        this.handle = handle;
        registry.register(this, () => runtime.call("swift_ffi_WebHost_release", handle), this);
    }
    /** @internal */
    borrowHandle() {
        if (this.handle === 0)
            throw new Error("WebHost used after close()");
        return this.handle;
    }
    /** Releases the underlying Swift instance. Idempotent. */
    close() {
        if (this.handle !== 0) {
            registry.unregister(this);
            this.runtime.call("swift_ffi_WebHost_release", this.handle);
            this.handle = 0;
        }
    }
    [Symbol.dispose]() {
        this.close();
    }
    measureText(text, fontSize, weight, wrapWidth) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, text);
        Types.double.encode(w, fontSize);
        Types.int32.encode(w, weight);
        Types.double.encode(w, wrapWidth);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 0, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(TextMetricsType, result);
    }
    imageInfo(source, isRemote) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, source);
        Types.bool.encode(w, isRemote);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 1, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(ImageInfoValueType, result);
    }
    syncHostViews(viewsJSON) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, viewsJSON);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 2, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    beginTextInput(text, x, y, width, height, fontSize) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, text);
        Types.double.encode(w, x);
        Types.double.encode(w, y);
        Types.double.encode(w, width);
        Types.double.encode(w, height);
        Types.double.encode(w, fontSize);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 3, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    endTextInput() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 4, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    scheduleRender() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 5, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    setColorScheme(dark) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.bool.encode(w, dark);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 6, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    now() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 7, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.double, result);
    }
    rasterize(spec) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, spec);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 8, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.bytes, result);
    }
    storageGet(key) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, key);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 9, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(StoredValueType, result);
    }
    storageSet(key, value) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, key);
        Types.string.encode(w, value);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 10, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    log(message) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, message);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 11, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    openURL(url) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, url);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 12, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    platformCommand(key, value) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, key);
        Types.string.encode(w, value);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 13, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    epochMillis() {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 14, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
        return decodeWith(Types.double, result);
    }
    renderTree(tree) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.bytes.encode(w, tree);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 15, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
    registerImage(source, bytes) {
        const handle = this.borrowHandle();
        const w = new BlobWriter();
        Types.string.encode(w, source);
        Types.bytes.encode(w, bytes);
        const staged = stageBytes(this.runtime, w.data());
        const box = this.runtime.call("swift_ffi_WebHost_invoke", handle, 16, staged.ptr, staged.len);
        staged.drop();
        const result = takeBytes(this.runtime, box);
        const failure = errorMessageOf(result);
        if (failure !== null)
            throw new SwiftError(failure);
    }
}
/** Wraps a consumer-implemented `WebHost` as the ordinal
 * dispatcher Swift's foreign proxy calls (method ordinal leads the
 * arguments). */
export function makeDispatcher_WebHost(impl, runtime) {
    return (args) => {
        const r = new BlobReader(args);
        switch (Types.int32.decode(r)) {
            case 0: {
                const a0 = Types.string.decode(r);
                const a1 = Types.double.decode(r);
                const a2 = Types.int32.decode(r);
                const a3 = Types.double.decode(r);
                return encodeWith(TextMetricsType, impl.measureText(a0, a1, a2, a3));
            }
            case 1: {
                const a0 = Types.string.decode(r);
                const a1 = Types.bool.decode(r);
                return encodeWith(ImageInfoValueType, impl.imageInfo(a0, a1));
            }
            case 2: {
                const a0 = Types.string.decode(r);
                impl.syncHostViews(a0);
                return new Uint8Array(0);
            }
            case 3: {
                const a0 = Types.string.decode(r);
                const a1 = Types.double.decode(r);
                const a2 = Types.double.decode(r);
                const a3 = Types.double.decode(r);
                const a4 = Types.double.decode(r);
                const a5 = Types.double.decode(r);
                impl.beginTextInput(a0, a1, a2, a3, a4, a5);
                return new Uint8Array(0);
            }
            case 4: {
                impl.endTextInput();
                return new Uint8Array(0);
            }
            case 5: {
                impl.scheduleRender();
                return new Uint8Array(0);
            }
            case 6: {
                const a0 = Types.bool.decode(r);
                impl.setColorScheme(a0);
                return new Uint8Array(0);
            }
            case 7: {
                return encodeWith(Types.double, impl.now());
            }
            case 8: {
                const a0 = Types.string.decode(r);
                return encodeWith(Types.bytes, impl.rasterize(a0));
            }
            case 9: {
                const a0 = Types.string.decode(r);
                return encodeWith(StoredValueType, impl.storageGet(a0));
            }
            case 10: {
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                impl.storageSet(a0, a1);
                return new Uint8Array(0);
            }
            case 11: {
                const a0 = Types.string.decode(r);
                impl.log(a0);
                return new Uint8Array(0);
            }
            case 12: {
                const a0 = Types.string.decode(r);
                impl.openURL(a0);
                return new Uint8Array(0);
            }
            case 13: {
                const a0 = Types.string.decode(r);
                const a1 = Types.string.decode(r);
                impl.platformCommand(a0, a1);
                return new Uint8Array(0);
            }
            case 14: {
                return encodeWith(Types.double, impl.epochMillis());
            }
            case 15: {
                const a0 = Types.bytes.decode(r);
                impl.renderTree(a0);
                return new Uint8Array(0);
            }
            case 16: {
                const a0 = Types.string.decode(r);
                const a1 = Types.bytes.decode(r);
                impl.registerImage(a0, a1);
                return new Uint8Array(0);
            }
        }
        throw new SwiftError("unknown WebHost method ordinal");
    };
}
/** Builders wrapping host implementations for injection. */
export const Dependencies = {
    networkService: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_platform_services_NetworkService",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_NetworkService(impl, runtime)(args);
            },
        };
    },
    fileService: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_platform_services_FileService",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_FileService(impl, runtime)(args);
            },
        };
    },
    keychainService: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_platform_services_KeychainService",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_KeychainService(impl, runtime)(args);
            },
        };
    },
    analyticsService: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_platform_services_AnalyticsService",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_AnalyticsService(impl, runtime)(args);
            },
        };
    },
    configurationService: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_platform_services_ConfigurationService",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_ConfigurationService(impl, runtime)(args);
            },
        };
    },
    imagePickerService: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_platform_services_ImagePickerService",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_ImagePickerService(impl, runtime)(args);
            },
        };
    },
    deviceMotionService: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_platform_services_DeviceMotionService",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_DeviceMotionService(impl, runtime)(args);
            },
        };
    },
    preferencesService: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_platform_services_PreferencesService",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_PreferencesService(impl, runtime)(args);
            },
        };
    },
    timerService: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_platform_services_TimerService",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_TimerService(impl, runtime)(args);
            },
        };
    },
    oAuthService: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_platform_services_OAuthService",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_OAuthService(impl, runtime)(args);
            },
        };
    },
    gPUWebHost: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_GPUWebHost",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_GPUWebHost(impl, runtime)(args);
            },
        };
    },
    webHost: (provide, lazy = true) => {
        let impl;
        return {
            key: "swift_ffi_WebHost",
            lazy,
            dispatcher: (args, runtime) => {
                if (!impl)
                    impl = provide();
                return makeDispatcher_WebHost(impl, runtime)(args);
            },
        };
    },
};
export class SwiftUI {
    runtime;
    /** @internal */
    constructor(runtime) {
        this.runtime = runtime;
    }
    installPlatformDependencies(networking, file, keychain, analytics, configuration) {
        const f0 = networking instanceof SwiftNetworkService ? [networking.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_NetworkService(networking, () => this.runtime))];
        const f1 = file instanceof SwiftFileService ? [file.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_FileService(file, () => this.runtime))];
        const f2 = keychain instanceof SwiftKeychainService ? [keychain.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_KeychainService(keychain, () => this.runtime))];
        const f3 = analytics instanceof SwiftAnalyticsService ? [analytics.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_AnalyticsService(analytics, () => this.runtime))];
        const f4 = configuration instanceof SwiftConfigurationService ? [configuration.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_ConfigurationService(configuration, () => this.runtime))];
        this.runtime.call("swift_ffi_platform_services_installPlatformDependencies", f0[0], f0[1], f1[0], f1[1], f2[0], f2[1], f3[0], f3[1], f4[0], f4[1]);
    }
    installPlatformImagePicker(imagePicker) {
        const f0 = imagePicker instanceof SwiftImagePickerService ? [imagePicker.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_ImagePickerService(imagePicker, () => this.runtime))];
        this.runtime.call("swift_ffi_platform_services_installPlatformImagePicker", f0[0], f0[1]);
    }
    installPlatformDeviceMotion(deviceMotion) {
        const f0 = deviceMotion instanceof SwiftDeviceMotionService ? [deviceMotion.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_DeviceMotionService(deviceMotion, () => this.runtime))];
        this.runtime.call("swift_ffi_platform_services_installPlatformDeviceMotion", f0[0], f0[1]);
    }
    installPlatformPreferences(preferences) {
        const f0 = preferences instanceof SwiftPreferencesService ? [preferences.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_PreferencesService(preferences, () => this.runtime))];
        this.runtime.call("swift_ffi_platform_services_installPlatformPreferences", f0[0], f0[1]);
    }
    installPlatformTimer(timer) {
        const f0 = timer instanceof SwiftTimerService ? [timer.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_TimerService(timer, () => this.runtime))];
        this.runtime.call("swift_ffi_platform_services_installPlatformTimer", f0[0], f0[1]);
    }
    installPlatformOAuth(oauth) {
        const f0 = oauth instanceof SwiftOAuthService ? [oauth.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_OAuthService(oauth, () => this.runtime))];
        this.runtime.call("swift_ffi_platform_services_installPlatformOAuth", f0[0], f0[1]);
    }
    gpuConnect(host) {
        const f0 = host instanceof SwiftGPUWebHost ? [host.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_GPUWebHost(host, () => this.runtime))];
        this.runtime.call("swift_ffi_gpuConnect", f0[0], f0[1]);
    }
    uuiSetDisplayScale(scale) {
        this.runtime.call("swift_ffi_uuiSetDisplayScale", scale);
    }
    uuiStart(host, renderer, width, height) {
        const f0 = host instanceof SwiftWebHost ? [host.borrowHandle(), 0] : [0, registerForeign(makeDispatcher_WebHost(host, () => this.runtime))];
        const b1 = stageString(this.runtime, renderer);
        this.runtime.call("swift_ffi_uuiStart", f0[0], f0[1], b1.ptr, b1.len, width, height);
        b1.drop();
    }
    uuiRender() {
        this.runtime.call("swift_ffi_uuiRender");
    }
    uuiMapSurfaceRender(id, camera, annotations, polygons, polylines, width, height) {
        const b0 = stageString(this.runtime, id);
        const b1 = stageString(this.runtime, camera);
        const b2 = stageString(this.runtime, annotations);
        const b3 = stageString(this.runtime, polygons);
        const b4 = stageString(this.runtime, polylines);
        this.runtime.call("swift_ffi_uuiMapSurfaceRender", b0.ptr, b0.len, b1.ptr, b1.len, b2.ptr, b2.len, b3.ptr, b3.len, b4.ptr, b4.len, width, height);
        b0.drop();
        b1.drop();
        b2.drop();
        b3.drop();
        b4.drop();
    }
    uuiSetScenePhase(phase) {
        const b0 = stageString(this.runtime, phase);
        this.runtime.call("swift_ffi_uuiSetScenePhase", b0.ptr, b0.len);
        b0.drop();
    }
    uuiSetColorScheme(dark) {
        this.runtime.call("swift_ffi_uuiSetColorScheme", dark ? 1 : 0);
    }
    uuiOpenURL(url) {
        const b0 = stageString(this.runtime, url);
        this.runtime.call("swift_ffi_uuiOpenURL", b0.ptr, b0.len);
        b0.drop();
    }
    uuiPointerEvent(kind, x, y) {
        this.runtime.call("swift_ffi_uuiPointerEvent", kind, x, y);
    }
    uuiWheelEvent(x, y, deltaX, deltaY) {
        this.runtime.call("swift_ffi_uuiWheelEvent", x, y, deltaX, deltaY);
    }
    uuiResize(width, height) {
        this.runtime.call("swift_ffi_uuiResize", width, height);
    }
    uuiTextChanged(text) {
        const b0 = stageString(this.runtime, text);
        this.runtime.call("swift_ffi_uuiTextChanged", b0.ptr, b0.len);
        b0.drop();
    }
    uuiTextSubmitted() {
        this.runtime.call("swift_ffi_uuiTextSubmitted");
    }
    uuiTextEnded() {
        this.runtime.call("swift_ffi_uuiTextEnded");
    }
    uuiHostEvent(id, value) {
        const b0 = stageString(this.runtime, id);
        const b1 = stageString(this.runtime, value);
        this.runtime.call("swift_ffi_uuiHostEvent", b0.ptr, b0.len, b1.ptr, b1.len);
        b0.drop();
        b1.drop();
    }
    uuiKeyEvent(id, value) {
        const b0 = stageString(this.runtime, id);
        const b1 = stageString(this.runtime, value);
        const r = this.runtime.call("swift_ffi_uuiKeyEvent", b0.ptr, b0.len, b1.ptr, b1.len);
        b0.drop();
        b1.drop();
        return r !== 0;
    }
}
/** Instantiates the reactor and returns the bridged API. `wasi`
 * merges over the built-in WASI shim, so a host can extend or
 * replace individual calls (clocks, fds, …) without forking. */
export async function load(wasm, options) {
    let memory;
    let runtime;
    // Buffer helpers for the dispatch channel: buffers arrive as
    // (ptr, len) borrowed and return packed as (len << 32) | ptr with
    // bytes from swift_ffi_alloc, ownership transferred to the guest.
    const foreignBytes = (ptr, len) => len === 0 ? new Uint8Array(0) : new Uint8Array(memory.buffer, ptr, len).slice();
    const foreignString = (ptr, len) => len === 0 ? "" : decoder.decode(new Uint8Array(memory.buffer, ptr, len));
    const packForeignBytes = (bytes) => {
        if (bytes.length === 0)
            return 0n;
        const ptr = runtime.call("swift_ffi_alloc", bytes.length);
        new Uint8Array(memory.buffer, ptr, bytes.length).set(bytes);
        return (BigInt(bytes.length) << 32n) | BigInt(ptr >>> 0);
    };
    const swiftFFIImports = {
        closure_invoke: (id, argsPtr, argsLen) => {
            const dispatcher = foreignObjects.get(id);
            let result;
            try {
                if (!dispatcher)
                    throw new Error(`no foreign object ${id}`);
                result = dispatcher(foreignBytes(argsPtr, argsLen));
            }
            catch (error) {
                result = encodeErrorBlob(error instanceof Error ? error.message : String(error));
            }
            return packForeignBytes(result);
        },
        foreign_release: (id) => {
            foreignObjects.delete(id);
        },
        dependency_get: (keyPtr, keyLen) => {
            const dep = options?.dependencies?.[foreignString(keyPtr, keyLen)];
            if (!dep)
                return 0n;
            const w = new BlobWriter();
            w.header(Tags.list, 0);
            w.i64(3n);
            Types.bool.encode(w, dep.lazy);
            Types.string.encode(w, dep.key);
            Types.int32.encode(w, registerForeign((args) => dep.dispatcher(args, () => runtime)));
            return packForeignBytes(w.data());
        },
        task_enqueue: (job) => {
            queueMicrotask(() => {
                runtime.call("swift_ffi_task_run", job);
            });
        },
        // A timed job (Task.sleep): run it once the delay is up.
        task_enqueue_after: (job, delayMs) => {
            setTimeout(() => {
                runtime.call("swift_ffi_task_run", job);
            }, Math.max(0, delayMs));
        },
        async_complete: (callId, blobPtr, blobLen) => {
            const pending = pendingCalls.get(callId);
            pendingCalls.delete(callId);
            pending.resolve(pending.decode(foreignBytes(blobPtr, blobLen)));
        },
    };
    const imports = {
        wasi_snapshot_preview1: wasiShim(() => {
            if (!memory)
                throw new Error("wasm memory accessed before instantiation");
            return memory;
        }, options?.wasi),
        swift_ffi: swiftFFIImports,
    };
    const module = wasm instanceof WebAssembly.Module ? wasm : await WebAssembly.compile(wasm);
    const instance = await WebAssembly.instantiate(module, imports);
    memory = instance.exports.memory;
    instance.exports._initialize();
    runtime = new Runtime(instance.exports);
    // Register the interfaces' dependency-proxy factories (docs/wasm_di.md).
    runtime.call("swift_ffi_platform_services_register_NetworkService");
    runtime.call("swift_ffi_platform_services_register_FileService");
    runtime.call("swift_ffi_platform_services_register_KeychainService");
    runtime.call("swift_ffi_platform_services_register_AnalyticsService");
    runtime.call("swift_ffi_platform_services_register_ConfigurationService");
    runtime.call("swift_ffi_platform_services_register_ImagePickerService");
    runtime.call("swift_ffi_platform_services_register_DeviceMotionService");
    runtime.call("swift_ffi_platform_services_register_PreferencesService");
    runtime.call("swift_ffi_platform_services_register_TimerService");
    runtime.call("swift_ffi_platform_services_register_OAuthService");
    runtime.call("swift_ffi_register_GPUWebHost");
    runtime.call("swift_ffi_register_WebHost");
    return new SwiftUI(runtime);
}
